<?php

namespace App\Support\Options;

/**
 * SUMBER TUNGGAL pilihan terminologi Rujukan Berbasis Kompetensi (jalur FHIR
 * SATUSEHAT: Ranap & IGD). Dipakai bersama panel RI, UGD, dan RJ-FHIR —
 * jangan menyalin daftarnya ke salah satu panel.
 *
 * ACUAN: Buku Panduan SATUSEHAT "Rujukan Pasien — Rawat Jalan, Rawat Inap, dan
 * Rawat Darurat" versi 6.1 (21 Agustus 2026).
 */
final class RujukanKompetensiOptions
{
    /**
     * Lima pertanyaan kriteria GAWAT DARURAT (Questionnaire Q100, linkId 000001–000005) —
     * dicentang minimal satu saat merujuk ke IGD; IGD tidak memvalidasi ICD-9/10.
     * Dipakai ketiga panel FHIR (RJ/UGD/RI) dan cetak Surat Pengantar Rujukan.
     */
    public const PERTANYAAN_IGD = [
        '000001' => 'Mengancam nyawa, membahayakan diri dan orang lain/lingkungan',
        '000002' => 'Adanya gangguan pada jalan nafas, pernafasan, dan sirkulasi',
        '000003' => 'Adanya penurunan kesadaran',
        '000004' => 'Adanya gangguan hemodinamik',
        '000005' => 'Memerlukan tindakan segera',
    ];

    /** Kriteria rujukan RANAP (tepat satu) — kunci = nilai formRujukan.kriteriaPilih jalur FHIR. */
    public const KRITERIA_RANAP = [
        'terapi'   => 'Terapi/Pengobatan',
        'tindakan' => 'Tindakan Medis (ICD-9-CM)',
        'upaya'    => 'Upaya Diagnosis',
    ];

    /**
     * Kelompok Layanan — Task.input.valueCoding pada Task Pencarian Kandidat
     * Fasyankes Rujukan (playbook v6.0, Lampiran 4).
     *
     * TK000562 adalah kode TIPE input-nya ("Kelompok Layanan"), BUKAN salah satu
     * nilai di daftar ini — jangan sampai tertukar.
     */
    public const KELOMPOK_LAYANAN = [
        'TK000563' => 'Jantung dan Pembuluh Darah',
        'TK000564' => 'Paru-Pernapasan',
        'TK000565' => 'Uronefro-Ginjal',
        'TK000566' => 'Neonatus',
        'TK000567' => 'Neoplasma',
        'TK000568' => 'Ibu dan Ginekologi',
        'TK000569' => 'Muskuloskeletal dan Jaringan Lunak',
        'TK000570' => 'THT',
        'TK000571' => 'Mata',
        'TK000572' => 'Kulit dan Kelamin',
        'TK000573' => 'Saraf Neurosain',
        'TK000574' => 'Infeksi dan Parasit',
        'TK000575' => 'Pencernaan dan Hepatobiliar',
        'TK000576' => 'Hematologi',
        'TK000577' => 'Alergi dan Rhematologi',
        'TK000578' => 'Rekonstruksi dan Estetika',
        'TK000579' => 'Keracunan',
        'TK000580' => 'Endocrine, Nutrition, dan Metabolik',
        'TK000581' => 'Luka Bakar - Burn',
        'TK000582' => 'Trauma',
        'TK000583' => 'Jiwa',
        'TK000584' => 'Gigi dan Mulut',
        'TK000585' => 'Forensik',
        'TK000586' => 'Rehabilitasi',
    ];

    /** Label lengkap seperti tertulis di playbook (dipakai sebagai display FHIR). */
    public static function kelompokLayananDisplay(string $kodeKelompok): string
    {
        $namaKelompok = self::KELOMPOK_LAYANAN[$kodeKelompok] ?? '';

        return $namaKelompok === '' ? '' : 'Kelompok Layanan ' . $namaKelompok;
    }

    /**
     * Jenis Tenaga Kesehatan Pelaksana Rujukan — ServiceRequest.performerType,
     * kode SNOMED dari sheet "HealthcareProfessional ECL" (Lampiran Terminologi
     * Occupation SNOMED).
     *
     * DAFTAR INI SENGAJA BELUM LENGKAP. Sheet occupation-nya tidak ikut dibagikan
     * di grup — yang ada barulah satu kode yang TERBUKTI diterima SATUSEHAT
     * (dipakai di tiga contoh Postman resmi dan pada payload faskes lain yang
     * kirimannya berhasil 21/08/2026).
     *
     * Menebak kode SNOMED lain berbahaya di dua sisi: ditolak validator karena
     * edisi SNOMED SATUSEHAT tertinggal, atau lolos tapi mencatat jenis tenaga
     * kesehatan yang KELIRU di rekam medis nasional. Karena itu bila petugas tidak
     * memilih, field-nya tidak dikirim sama sekali (dan itu sah — contoh payload
     * faskes lain yang berhasil pun tanpa field ini).
     *
     * Lengkapi daftar ini begitu sheet resminya didapat.
     */
    public const PERFORMER_TYPE = [
        '39677007' => 'Internal medicine specialist',
    ];

    /**
     * Katalog kode layanan `clinical-speciality` (CarePlan.activity[].detail.code) —
     * LENGKAP, 307 kode: 29 kode KELOMPOK (L01–L43) + 278 kode layanan (LY…).
     *
     * Sumber: Google Sheet "Poli Tujuan (clinical-speciality)" yang dibagikan tim
     * SATUSEHAT di grup 03/06/26 (ditegaskan lagi 18/06/26):
     * docs.google.com/spreadsheets/d/1wVb-PSwWsg2I9mdpxRQ9r_E7IHkoTFyBXcJfGTpa4-k
     * Disalin 22/09/26. Kode kelompok ikut sah dikirim — L03 dipakai IGD sejak awal
     * dan diterima server; LY010/LY026/LY133/LY246 terbukti dipakai faskes lain.
     *
     * Petugas TETAP boleh mengetik kode sendiri ("ketik manual"): sheet-nya bisa
     * bertambah tanpa pemberitahuan, dan record lama tak boleh jadi tak terbaca.
     * Memperbarui: unduh sheet sebagai CSV lalu bangkitkan ulang dua konstanta ini.
     */
    public const CLINICAL_SPECIALITY = [
        // Kode kelompok
        'L01' => 'Pelayanan Medik Umum',
        'L03' => 'Pelayanan Gawat Darurat',
        'L04' => 'Pelayanan Medik Spesialis Dasar',
        'L05' => 'Pelayanan Spesialis Penunjang Medik',
        'L06' => 'Pelayanan Medik Spesialis Lain',
        'L08' => 'Pelayanan Medik Spesialis Lain berupa Pelayanan Spesialistik Mata di RS Mata',
        'L09' => 'Pelayanan Medik Spesialis Lain berupa Pelayanan Spesialistik Jantung dan Pembuluh Darah di RS Jantung',
        'L10' => 'Pelayanan Medik Spesialis Lain berupa Pelayanan Spesialistik Jiwa dan KO',
        'L11' => 'Pelayanan Medik Spesialis Lain berupa Pelayanan Spesialistik Paru di RS Paru',
        'L12' => 'Pelayanan Medik Spesialis Lain berupa Pelayanan Spesialistik Orthopedi di RS Orthopedi',
        'L13' => 'Pelayanan Medik Spesialis Gigi dan Mulut',
        'L14' => 'Pelayanan Medik Subspesialis Bedah',
        'L15' => 'Pelayanan Medik Subspesialistik Anak',
        'L16' => 'Pelayanan Medik Subspesialistik Kebidanan dan Kandungan',
        'L17' => 'Pelayanan Medik Subspesialistik Mata',
        'L18' => 'Pelayanan Medik Subspesialis THT',
        'L19' => 'Pelayanan Medik Subspesialis Syaraf',
        'L27' => 'Pelayanan Rumah Sakit KO',
        'L31' => 'Pelayanan Fasilitas Penunjang di RS Stroke',
        'L33' => 'Pelayanan Medik Subspesialis Penyakit Dalam',
        'L35' => 'Pelayanan Medik Subspesialis Anestesi dan Terapi Intensif',
        'L36' => 'Pelayanan Medik Subspesialis Bedah Anak',
        'L37' => 'Pelayanan Medik Subspesialis Bedah Plastik',
        'L38' => 'Pelayanan Medik Subspesialis Kedokteran Fisik dan Rehabilitasi',
        'L39' => 'Pelayanan Medik Subspesialis Kedokteran Nuklir',
        'L40' => 'Pelayanan Medik Subspesialis Kulit dan Kelamin',
        'L41' => 'Pelayanan Medik Subspesialis Patologi Klinik',
        'L42' => 'Pelayanan Medik Subspesialis Radiologi',
        'L43' => 'Pelayanan Medik Subspesialis Urologi',
        // Kode layanan
        'LY001' => 'Umum - Pelayanan medik dasar / umum',
        'LY002' => 'Umum - Pelayanan medik gigi mulut',
        'LY003' => 'Umum - Pelayanan KIA/KB',
        'LY007' => 'Gawat Darurat - Pelayanan Gawat Darurat Umum 24 jam & 7 hari seminggu',
        'LY010' => 'Spesialis - Penyakit dalam',
        'LY011' => 'Spesialis - Kesehatan anak',
        'LY012' => 'Spesialis - Bedah',
        'LY013' => 'Spesialis - Obstetri dan ginekologi',
        'LY014' => 'Spesialis Penunjang - Anestesi',
        'LY015' => 'Spesialis Penunjang - Radiologi',
        'LY016' => 'Spesialis Penunjang - Patologi Klinik',
        'LY017' => 'Spesialis Penunjang - Patologi Anatomi',
        'LY018' => 'Spesialis Penunjang - Rehabilitasi Medik',
        'LY314' => 'Spesialis Penunjang - Mikrobiologi Klinik',
        'LY019' => 'Spesialis - Mata',
        'LY020' => 'Spesialis - Paru',
        'LY021' => 'Spesialis - Kulit dan Kelamin',
        'LY022' => 'Spesialis - Kedokteran Jiwa / Psikiatri/ Psikogeriatri/ NAPZA',
        'LY023' => 'Spesialis - Orthopedi',
        'LY024' => 'Spesialis - Telinga Hidung Tenggorok Kepala Leher',
        'LY025' => 'Spesialis - Saraf',
        'LY026' => 'Spesialis - Jantung dan Pembuluh Darah',
        'LY027' => 'Spesialis - Kedokteran Forensik',
        'LY028' => 'Spesialis - Urologi',
        'LY096' => 'Spesialis - Bedah Plastik Rekonstruksi dan Estetika',
        'LY097' => 'Spesialis - Bedah Saraf',
        'LY183' => 'Spesialis - Program Terapi Rumatan Metadon (PTRM)',
        'LY276' => 'Spesialis - Bedah thorax kardiak dan vaskuler',
        'LY277' => 'Spesialis - Bedah Anak',
        'LY279' => 'Spesialis - Radioterapi/Onkologi Radiasi',
        'LY280' => 'Spesialis - Radiologi Kedokteran Gigi',
        'LY281' => 'Spesialis - Parasitologi Klinik',
        'LY282' => 'Spesialis - Farmakologi klinik',
        'LY287' => 'Spesialis - Kedokteran Nuklir',
        'LY315' => 'Spesialis - Laboratorium Gizi',
        'LY316' => 'Spesialis - Kedokteran Okupasi',
        'LY644' => 'Spesialis - Emergensi',
        'LY039' => 'Mata - Mata Infeksi dan Imunologi',
        'LY040' => 'Mata - Mata Glaukoma',
        'LY041' => 'Mata - Bedah Katarak',
        'LY042' => 'Mata - Bedah vitreo retina lanjut',
        'LY043' => 'Mata - Mata Komunitas',
        'LY044' => 'Mata - Mata Pediatrik',
        'LY046' => 'Mata - Onkologi Rekontruksi Mata',
        'LY116' => 'Mata - Refraksi dan Lensa Kontak',
        'LY118' => 'Mata - Kornea Lensa dan Bedah refraktif',
        'LY126' => 'Mata - Oftamologi Komunitas',
        'LY299' => 'Mata - Mata Strabismus',
        'LY300' => 'Mata - Saraf Mata',
        'LY047' => 'Jantung - Jantung konservatif',
        'LY048' => 'Jantung - Jantung Intervensi',
        'LY049' => 'Jantung - Jantung koroner',
        'LY050' => 'Jantung - Gagal Jantung Kronik',
        'LY051' => 'Jantung - Jantung Hipertensi',
        'LY052' => 'Jantung - Jantung Aritmia dan reprogram alat pacu jantung',
        'LY053' => 'Jantung - Kardiometabolik',
        'LY054' => 'Jantung - Jantung Vaskuler',
        'LY055' => 'Jantung - Jantung Valvular',
        'LY056' => 'Jantung - Pasca intervensi non bedah (Jantung)',
        'LY057' => 'Jantung - Pasca Operasi CABG (Jantung)',
        'LY058' => 'Jantung - Pasca Operasi katup (Jantung)',
        'LY059' => 'Jantung - Pasca operasi Pediatrik (Jantung)',
        'LY061' => 'Jantung - Jantung perikard',
        'LY062' => 'Jantung - Penyakit Jantung Pada Kehamilan',
        'LY302' => 'Jantung - Bedah jantung anak dan PJB',
        'LY303' => 'Jantung - Bedah jantung dewasa',
        'LY304' => 'Jantung - Prevensi Rehabilitasi Jantung',
        'LY065' => 'Jiwa & KO - Pelayanan kesehatan tumbuh kembang anak dan remaja',
        'LY066' => 'Jiwa & KO - Pelayanan kesehatan jiwa dewasa',
        'LY067' => 'Jiwa & KO - Pelayanan kesehatan jiwa lansia',
        'LY068' => 'Jiwa & KO - Gangguan mental organik',
        'LY069' => 'Jiwa & KO - Pelayanan psikologi dan psikometri',
        'LY071' => 'Jiwa & KO - Pelayanan kesehatan jiwa masyarakat',
        'LY072' => 'Jiwa & KO - Pelayanan konseling dan psikoterapi',
        'LY073' => 'Jiwa & KO - Rehab Mental',
        'LY308' => 'Jiwa & KO - Forensik Adiksi',
        'LY006' => 'Paru - Infeksi Paru',
        'LY075' => 'Paru - Paru Asma dan PPOK',
        'LY076' => 'Paru - Paru Onkologi',
        'LY077' => 'Paru - Paru Fisiologi',
        'LY078' => 'Paru - Penyakit paru akibat kerja',
        'LY079' => 'Paru - Paru Imunologi',
        'LY080' => 'Paru - Paru Intervensi',
        'LY081' => 'Orthopedi - Lower Extremity Surgery (Hip and Knee)',
        'LY082' => 'Orthopedi - Spine Surgery',
        'LY083' => 'Orthopedi - Hand and Micro Surgery',
        'LY084' => 'Orthopedi - Paediatric Surgery (Ortophaedi)',
        'LY309' => 'Orthopedi - Knee and Ankle',
        'LY310' => 'Orthopedi - Sport, Shoulder, and Elbow',
        'LY311' => 'Orthopedi - Tumor Muskuloskeletal',
        'LY086' => 'Gigi dan Mulut - Bedah Mulut',
        'LY087' => 'Gigi dan Mulut - Konservasi / endodonsi',
        'LY088' => 'Gigi dan Mulut - Orthodonti',
        'LY089' => 'Gigi dan Mulut - Periodonti',
        'LY090' => 'Gigi dan Mulut - Prosthodonti',
        'LY091' => 'Gigi dan Mulut - Pedodonsi',
        'LY092' => 'Gigi dan Mulut - Penyakit Mulut',
        'LY095' => 'Bedah - Bedah vaskular',
        'LY240' => 'Bedah - Bedah digestif',
        'LY241' => 'Bedah - Bedah onkologi',
        'LY098' => 'Anak - Perinatologi',
        'LY099' => 'Anak - Neurologi',
        'LY100' => 'Anak - Hemato-Onkologi',
        'LY101' => 'Anak - Nefrologi',
        'LY103' => 'Anak - Respirologi',
        'LY104' => 'Anak - Alergi Imunologi',
        'LY105' => 'Anak - Endokrin',
        'LY106' => 'Anak - Nutrisi dan Metabolik',
        'LY107' => 'Anak - Kardiologi Anak',
        'LY109' => 'Anak - Infeksi dan Penyakit Tropis',
        'LY110' => 'Anak - Tumbuh Kembang dan Pediatri Sosial',
        'LY242' => 'Anak - Pencitraan Anak',
        'LY317' => 'Anak - Neonatologi',
        'LY318' => 'Anak - Emergensi dan Rawat Intensif Anak',
        'LY111' => 'Kebidanan dan Kandungan - Kedokteran Fetomaternal',
        'LY112' => 'Kebidanan dan Kandungan - Onkologi Ginekologi',
        'LY113' => 'Kebidanan dan Kandungan - Fertilitas Endokrinologi Reproduksi',
        'LY114' => 'Kebidanan dan Kandungan - Obstetri Ginekologi sosial',
        'LY115' => 'Kebidanan dan Kandungan - Uro-ginekologi Rekonstruksi',
        'LY120' => 'Mata - Vitreo Retina',
        'LY121' => 'Mata - Strabismus',
        'LY125' => 'Mata - Pediatrik Oftamologi',
        'LY127' => 'THT - Bedah THT KL dan Rekonstruksi',
        'LY129' => 'THT - BERA (Brain Evoke Response Audimetri)',
        'LY130' => 'THT - E.N.G (Electric Nistamografi)',
        'LY131' => 'THT - Audiovestibuler',
        'LY132' => 'THT - Hearing Aid Center',
        'LY133' => 'Syaraf - Stroke dan Cerebro Vaskuler',
        'LY134' => 'Syaraf - Neuro fisiologi',
        'LY135' => 'Syaraf - Neuro emergency / intensive',
        'LY136' => 'Syaraf - Neuro restorasi/fungsi luhur',
        'LY137' => 'Syaraf - Neuro optalmologi / otologi',
        'LY138' => 'Syaraf - Neuro onkologi',
        'LY139' => 'Syaraf - Epilepsi',
        'LY198' => 'KO - Isolasi Pasien Gaduh Gelisah',
        'LY231' => 'Stroke - Akupuntur',
        'LY232' => 'Stroke - Kedokteran Olah raga',
        'LY645' => 'Stroke - Neurorehabilitasi',
        'LY037' => 'Penyakit Dalam - Dialisis/ CAPD',
        'LY102' => 'Penyakit Dalam - Gastroenterologi Hepatologi',
        'LY243' => 'Penyakit Dalam - Alergi Imunologi',
        'LY245' => 'Penyakit Dalam - Geriatri',
        'LY246' => 'Penyakit Dalam - Ginjal dan Hipertensi',
        'LY247' => 'Penyakit Dalam - Hemato-Onkologi',
        'LY248' => 'Penyakit Dalam - Kardiovaskuler',
        'LY249' => 'Penyakit Dalam - Metabolik Endokrin',
        'LY250' => 'Penyakit Dalam - Psikosomatik',
        'LY251' => 'Penyakit Dalam - Pulmonologi',
        'LY252' => 'Penyakit Dalam - Reumatologi',
        'LY312' => 'Penyakit Dalam - Paliatif',
        'LY330' => 'Anak - Anak Gastro-Hepatologi',
        'LY331' => 'Anastesi - Intensive care',
        'LY332' => 'Anastesi - Regional anestesi',
        'LY333' => 'Anastesi - Kardiovaskular anestesi',
        'LY334' => 'Anastesi - Terapi nyeri',
        'LY335' => 'Anastesi - Pediatrik anestesi',
        'LY336' => 'Anastesi - Neuroanestesi',
        'LY337' => 'Anastesi - Obstetrik anestesi',
        'LY338' => 'Anak - Bedah digestif anak',
        'LY339' => 'Anak - Urogenital anak',
        'LY340' => 'Bedah Plastik - Bedah plastik rekonstruksi dan estetika kraniomaksilofasial',
        'LY341' => 'Bedah Plastik - Bedah plastik rekonstruksi dan estetika luka bakar dan luka',
        'LY342' => 'Bedah Plastik - Bedah plastik rekonstruksi dan estetika rekonstruksi bedah mikro dan onkoplasti',
        'LY343' => 'Bedah Plastik - Bedah plastik rekonstruksi dan estetika bedah tangan',
        'LY344' => 'Bedah Plastik - Bedah plastik rekonstruksi dan estetika genitalia eksterna',
        'LY345' => 'Bedah Plastik - Bedah plastik rekonstruksi dan estetika bedah estetik lanjut',
        'LY346' => 'Syaraf - Bedah saraf neurotrauma',
        'LY347' => 'Syaraf - Bedah saraf neuro onkologi',
        'LY348' => 'Syaraf - Bedah saraf neurospine',
        'LY349' => 'Syaraf - Bedah saraf neurofungsional',
        'LY350' => 'Syaraf - Bedah saraf neuropediatri',
        'LY351' => 'Syaraf - Bedah saraf neurovaskular',
        'LY352' => 'Orthopedi - Bedah Orthopedi',
        'LY353' => 'Fisik dan Rehabilitasi - Kedokteran fisik dan rehabilitasi pediatri',
        'LY354' => 'Fisik dan Rehabilitasi - Kedokteran fisik dan rehabilitasi geriatri',
        'LY355' => 'Fisik dan Rehabilitasi - Kedokteran fisik dan rehabilitasi muskuloskeletal',
        'LY356' => 'Fisik dan Rehabilitasi - Kedokteran fisik dan rehabilitasi neomuskuler',
        'LY357' => 'Fisik dan Rehabilitasi - Kedokteran fisik dan rehabilitasi kardiorespirasi',
        'LY358' => 'Jantung dan Pembuluh Darah - Ekokardiografi',
        'LY359' => 'Jantung dan Pembuluh Darah - Kardiologi intervensi',
        'LY360' => 'Jiwa dan KO - Neuropsikiatri dan Psikometri',
        'LY361' => 'Jiwa dan KO - Kesehatan jiwa anak dan remaja',
        'LY362' => 'Jiwa dan KO - Psikiatri adiksi',
        'LY363' => 'Jiwa dan KO - Psikoterapi',
        'LY364' => 'Jiwa dan KO - Psikiatri forensik',
        'LY365' => 'Jiwa dan KO - Psikiatri komunitas',
        'LY366' => 'Nuklir - Kedokteran nuklir onkologi',
        'LY367' => 'Nuklir - Kedokteran nuklir kardiologi nuklir',
        'LY368' => 'Nuklir - Kedokteran nuklir pediatrik',
        'LY369' => 'Kulit dan Kelamin - Dermatologi tropis',
        'LY370' => 'Kulit dan Kelamin - Venereologi',
        'LY371' => 'Kulit dan Kelamin - Dermato alergi imunologi',
        'LY372' => 'Kulit dan Kelamin - Dermatologi anak',
        'LY373' => 'Kulit dan Kelamin - Dermatologi kosmetik dan estetik',
        'LY374' => 'Kulit dan Kelamin - Onkologi dan bedah kulit',
        'LY375' => 'Kulit dan Kelamin - Dermatologi Geriatrik',
        'LY376' => 'Kulit dan Kelamin - Dermatopatologi',
        'LY377' => 'Kulit dan Kelamin - Infeksi Menular Seksual',
        'LY378' => 'Mata - Pediatri onkologi strabismus',
        'LY379' => 'Mata - Rekonstruksi okuloplasti dan onkologi',
        'LY380' => 'Orthopedi - Orthopedic spine',
        'LY381' => 'Orthopedi - Hand, upper limb and microsurgery',
        'LY382' => 'Orthopedi - Orthopedic oncology',
        'LY383' => 'Orthopedi - Pediatric orthopedic',
        'LY384' => 'Orthopedi - Foot and ankle',
        'LY385' => 'Orthopedi - Advance orthopedic trauma',
        'LY386' => 'Orthopedi - Orthopedic sports injury',
        'LY387' => 'Orthopedi - Bio Orthopedic',
        'LY388' => 'Orthopedi - Trauma dan Rekonstruksi',
        'LY389' => 'Paru - Onkologi toraks',
        'LY390' => 'Paru - Faal Paru Klinik',
        'LY391' => 'Patologi Klinik - Patologi klinik mikrobiologi klinik dan penyakit infeksi',
        'LY392' => 'Patologi Klinik - Patologi klinik hematologi',
        'LY393' => 'Patologi Klinik - Patologi klinik metabolik endokrinologi',
        'LY394' => 'Patologi Klinik - Patologi klinik gastroenterohepatologi',
        'LY395' => 'Patologi Klinik - Patologi klinik imunologi',
        'LY396' => 'Patologi Klinik - Patologi klinik penyakit infeksi',
        'LY397' => 'Patologi Klinik - Patologi klinik hematologi onkologi',
        'LY398' => 'Patologi Klinik - Patologi klinik penyakit tropik dan Infeksi',
        'LY399' => 'Patologi Klinik - Patologi klinik endokrinologi',
        'LY400' => 'Penyakit Dalam - Penyakit dalam tropik infeksi',
        'LY401' => 'Radiologi - Neuroradiologi kepala leher',
        'LY402' => 'Radiologi - Radiologi abdomen',
        'LY403' => 'Radiologi - Radiologi intervensi',
        'LY404' => 'Radiologi - Radiologi anak',
        'LY405' => 'Radiologi - Radiologi toraks',
        'LY406' => 'Radiologi - Pencitraan payudara dan reproduksi perempuan',
        'LY407' => 'Radiologi - Radiologi muskuloskeletal',
        'LY408' => 'Syaraf - Stroke dan neurovaskular',
        'LY409' => 'Syaraf - Neuroinfeksi dan imunologi',
        'LY410' => 'Syaraf - Neuropediatri',
        'LY411' => 'Syaraf - Nyeri',
        'LY412' => 'Syaraf - Nyeri kepala',
        'LY413' => 'Syaraf - Movement disorder/gangguan gerak',
        'LY414' => 'Syaraf - Sleep disorder',
        'LY415' => 'Syaraf - Neuro-otologi dan vertigo',
        'LY416' => 'Syaraf - Neurotrauma',
        'LY417' => 'Syaraf - Neurointensif',
        'LY418' => 'Syaraf - Neuroimaging',
        'LY419' => 'Syaraf - Neurogeriatri',
        'LY420' => 'Syaraf - Neurointervensi',
        'LY421' => 'Syaraf - Neurofisiologi Klinis',
        'LY422' => 'Syaraf - Neuromuskular, Saraf Perifer',
        'LY423' => 'Syaraf - Neuroinfeksi',
        'LY424' => 'Spesialis - Orthopedi dan traumatologi',
        'LY425' => 'Spesialis - Kedokteran forensik dan medikolegal',
        'LY426' => 'Spesialis - Anestesi dan terapi intensif',
        'LY427' => 'Spesialis - Kedokteran fisik dan rehabilitasi',
        'LY428' => 'Spesialis - Andrologi',
        'LY429' => 'Spesialis - Kedokteran kelautan',
        'LY430' => 'Spesialis - Kedokteran Keluarga',
        'LY431' => 'Spesialis - Kedokteran Penerbangan',
        'LY432' => 'Spesialis - Lainnya',
        'LY433' => 'THT - Otologi',
        'LY434' => 'THT - Rinologi',
        'LY435' => 'THT - Onkologi bedah kepala leher',
        'LY436' => 'THT - Laring faring',
        'LY437' => 'THT - Neurotologi',
        'LY438' => 'THT - Endoskopi bronkoesofagologi',
        'LY439' => 'THT - THT komunitas',
        'LY440' => 'THT - THT-KL plastik rekonstruksi',
        'LY441' => 'THT - Bedah kepala leher',
        'LY442' => 'THT - Pencitraan Kepala Leher',
        'LY443' => 'THT - Urologi onkologi',
        'LY444' => 'THT - Urologi pediatri',
        'LY445' => 'THT - Urologi wanita dan neuro-urologi',
        'LY446' => 'THT - Urologi rekonstruksi',
        'LY447' => 'THT - Urologi andrologi',
        'LY448' => 'Hemodialisa',
        'LY455' => 'Rekonstruksi',
        'LY449' => 'Radiologi Tr Urinariusgenitalia',
        'LY450' => 'Radiologi Tr Digestivus',
        'LY451' => 'Nutrisi pada Critical Care',
        'LY452' => 'HIV-ODHA',
        'LY453' => 'Imunologi Klinik',
        'LY454' => 'Sarana Kemoterapi',
        'LY458' => 'Kusta',
        'LY456' => 'Day care',
    ];

    /**
     * Kode induk (kelompok) tiap kode layanan LY… — untuk mengelompokkan pilihan.
     * Kode layanan yang di sheet tak berinduk ('-') sengaja tidak tercantum.
     */
    public const CLINICAL_SPECIALITY_INDUK = [
        'LY001' => 'L01',
        'LY002' => 'L01',
        'LY003' => 'L01',
        'LY007' => 'L03',
        'LY010' => 'L04',
        'LY011' => 'L04',
        'LY012' => 'L04',
        'LY013' => 'L04',
        'LY014' => 'L05',
        'LY015' => 'L05',
        'LY016' => 'L05',
        'LY017' => 'L05',
        'LY018' => 'L05',
        'LY314' => 'L05',
        'LY019' => 'L06',
        'LY020' => 'L06',
        'LY021' => 'L06',
        'LY022' => 'L06',
        'LY023' => 'L06',
        'LY024' => 'L06',
        'LY025' => 'L06',
        'LY026' => 'L06',
        'LY027' => 'L06',
        'LY028' => 'L06',
        'LY096' => 'L06',
        'LY097' => 'L06',
        'LY183' => 'L06',
        'LY276' => 'L06',
        'LY277' => 'L06',
        'LY279' => 'L06',
        'LY280' => 'L06',
        'LY281' => 'L06',
        'LY282' => 'L06',
        'LY287' => 'L06',
        'LY315' => 'L06',
        'LY316' => 'L06',
        'LY644' => 'L06',
        'LY039' => 'L08',
        'LY040' => 'L08',
        'LY041' => 'L08',
        'LY042' => 'L08',
        'LY043' => 'L08',
        'LY044' => 'L08',
        'LY046' => 'L08',
        'LY116' => 'L08',
        'LY118' => 'L08',
        'LY126' => 'L08',
        'LY299' => 'L08',
        'LY300' => 'L08',
        'LY047' => 'L09',
        'LY048' => 'L09',
        'LY049' => 'L09',
        'LY050' => 'L09',
        'LY051' => 'L09',
        'LY052' => 'L09',
        'LY053' => 'L09',
        'LY054' => 'L09',
        'LY055' => 'L09',
        'LY056' => 'L09',
        'LY057' => 'L09',
        'LY058' => 'L09',
        'LY059' => 'L09',
        'LY061' => 'L09',
        'LY062' => 'L09',
        'LY302' => 'L09',
        'LY303' => 'L09',
        'LY304' => 'L09',
        'LY065' => 'L10',
        'LY066' => 'L10',
        'LY067' => 'L10',
        'LY068' => 'L10',
        'LY069' => 'L10',
        'LY071' => 'L10',
        'LY072' => 'L10',
        'LY073' => 'L10',
        'LY308' => 'L10',
        'LY006' => 'L11',
        'LY075' => 'L11',
        'LY076' => 'L11',
        'LY077' => 'L11',
        'LY078' => 'L11',
        'LY079' => 'L11',
        'LY080' => 'L11',
        'LY081' => 'L12',
        'LY082' => 'L13',
        'LY083' => 'L12',
        'LY084' => 'L12',
        'LY309' => 'L12',
        'LY310' => 'L12',
        'LY311' => 'L12',
        'LY086' => 'L13',
        'LY087' => 'L13',
        'LY088' => 'L13',
        'LY089' => 'L13',
        'LY090' => 'L13',
        'LY091' => 'L13',
        'LY092' => 'L13',
        'LY095' => 'L14',
        'LY240' => 'L14',
        'LY241' => 'L14',
        'LY098' => 'L15',
        'LY099' => 'L15',
        'LY100' => 'L15',
        'LY101' => 'L15',
        'LY103' => 'L15',
        'LY104' => 'L15',
        'LY105' => 'L15',
        'LY106' => 'L15',
        'LY107' => 'L15',
        'LY109' => 'L15',
        'LY110' => 'L15',
        'LY242' => 'L15',
        'LY317' => 'L15',
        'LY318' => 'L15',
        'LY111' => 'L16',
        'LY112' => 'L16',
        'LY113' => 'L16',
        'LY114' => 'L16',
        'LY115' => 'L16',
        'LY120' => 'L17',
        'LY121' => 'L17',
        'LY125' => 'L17',
        'LY127' => 'L18',
        'LY129' => 'L18',
        'LY130' => 'L18',
        'LY131' => 'L18',
        'LY132' => 'L18',
        'LY133' => 'L19',
        'LY134' => 'L19',
        'LY135' => 'L19',
        'LY136' => 'L19',
        'LY137' => 'L19',
        'LY138' => 'L19',
        'LY139' => 'L19',
        'LY198' => 'L27',
        'LY231' => 'L31',
        'LY232' => 'L31',
        'LY645' => 'L31',
        'LY037' => 'L33',
        'LY102' => 'L33',
        'LY243' => 'L33',
        'LY245' => 'L33',
        'LY246' => 'L33',
        'LY247' => 'L33',
        'LY248' => 'L33',
        'LY249' => 'L33',
        'LY250' => 'L33',
        'LY251' => 'L33',
        'LY252' => 'L33',
        'LY312' => 'L33',
        'LY330' => 'L15',
        'LY331' => 'L35',
        'LY332' => 'L35',
        'LY333' => 'L35',
        'LY334' => 'L35',
        'LY335' => 'L35',
        'LY336' => 'L35',
        'LY337' => 'L35',
        'LY338' => 'L36',
        'LY339' => 'L36',
        'LY340' => 'L37',
        'LY341' => 'L37',
        'LY342' => 'L37',
        'LY343' => 'L37',
        'LY344' => 'L37',
        'LY345' => 'L37',
        'LY346' => 'L19',
        'LY347' => 'L19',
        'LY348' => 'L19',
        'LY349' => 'L19',
        'LY350' => 'L19',
        'LY351' => 'L19',
        'LY352' => 'L12',
        'LY353' => 'L38',
        'LY354' => 'L38',
        'LY355' => 'L38',
        'LY356' => 'L38',
        'LY357' => 'L38',
        'LY358' => 'L09',
        'LY359' => 'L09',
        'LY360' => 'L10',
        'LY361' => 'L10',
        'LY362' => 'L10',
        'LY363' => 'L10',
        'LY364' => 'L10',
        'LY365' => 'L10',
        'LY366' => 'L39',
        'LY367' => 'L39',
        'LY368' => 'L39',
        'LY369' => 'L40',
        'LY370' => 'L40',
        'LY371' => 'L40',
        'LY372' => 'L40',
        'LY373' => 'L40',
        'LY374' => 'L40',
        'LY375' => 'L40',
        'LY376' => 'L40',
        'LY377' => 'L40',
        'LY378' => 'L17',
        'LY379' => 'L17',
        'LY380' => 'L12',
        'LY381' => 'L12',
        'LY382' => 'L12',
        'LY383' => 'L12',
        'LY384' => 'L12',
        'LY385' => 'L12',
        'LY386' => 'L12',
        'LY387' => 'L12',
        'LY388' => 'L12',
        'LY389' => 'L11',
        'LY390' => 'L11',
        'LY391' => 'L41',
        'LY392' => 'L41',
        'LY393' => 'L41',
        'LY394' => 'L41',
        'LY395' => 'L41',
        'LY396' => 'L41',
        'LY397' => 'L41',
        'LY398' => 'L41',
        'LY399' => 'L41',
        'LY400' => 'L33',
        'LY401' => 'L42',
        'LY402' => 'L42',
        'LY403' => 'L42',
        'LY404' => 'L42',
        'LY405' => 'L42',
        'LY406' => 'L42',
        'LY407' => 'L42',
        'LY408' => 'L19',
        'LY409' => 'L19',
        'LY410' => 'L19',
        'LY411' => 'L19',
        'LY412' => 'L19',
        'LY413' => 'L19',
        'LY414' => 'L19',
        'LY415' => 'L19',
        'LY416' => 'L19',
        'LY417' => 'L19',
        'LY418' => 'L19',
        'LY419' => 'L19',
        'LY420' => 'L19',
        'LY421' => 'L19',
        'LY422' => 'L19',
        'LY423' => 'L19',
        'LY424' => 'L06',
        'LY425' => 'L06',
        'LY426' => 'L06',
        'LY427' => 'L06',
        'LY428' => 'L06',
        'LY429' => 'L06',
        'LY430' => 'L06',
        'LY431' => 'L06',
        'LY432' => 'L06',
        'LY433' => 'L18',
        'LY434' => 'L18',
        'LY435' => 'L18',
        'LY436' => 'L18',
        'LY437' => 'L18',
        'LY438' => 'L18',
        'LY439' => 'L18',
        'LY440' => 'L18',
        'LY441' => 'L18',
        'LY442' => 'L18',
        'LY443' => 'L43',
        'LY444' => 'L43',
        'LY445' => 'L43',
        'LY446' => 'L43',
        'LY447' => 'L43',
    ];

    /**
     * Katalog dikelompokkan untuk <optgroup>: label kelompok => [kode => nama].
     * Kode kelompoknya sendiri jadi pilihan pertama di grupnya (mis. L03 untuk IGD);
     * kode layanan tanpa induk dikumpulkan di "Layanan lain".
     */
    public static function clinicalSpecialityBerkelompok(): array
    {
        $grup = [];
        foreach (self::CLINICAL_SPECIALITY as $kode => $nama) {
            if (!str_starts_with($kode, 'LY')) {
                $grup[$kode . ' — ' . $nama][$kode] = $nama;
                continue;
            }
            $induk = self::CLINICAL_SPECIALITY_INDUK[$kode] ?? null;
            $label = $induk !== null ? $induk . ' — ' . (self::CLINICAL_SPECIALITY[$induk] ?? $induk) : 'Layanan lain';
            $grup[$label][$kode] = $nama;
        }

        return $grup;
    }
}
