-- Sample data Pemantauan Akses Ruang Server (RSTXN_AKSESSERVERS)
-- 50 kunjungan, periode Sep 2025 - Agu 2026, hari kerja & jam kerja.
--
-- HANYA TIGA ORANG: Anshary, Puji, Soim — seluruhnya petugas internal
-- IT/SIMRS, tak ada tamu dari luar. Karena itu kolom "didampingi" kosong:
-- aturan wajibDidampingi() hanya berlaku untuk pengunjung non-internal.
--
--   12x mendampingi kebersihan  (bulanan, Puji/Soim)
--   12x backup data             (bulanan, Anshary)
--    8x update program          (Anshary saja)
--   11x pengecekan hardware     (condong ke Soim - bidangnya)
--    7x pemantauan suhu         (tersebar, ketiganya)
--
-- Dihasilkan oleh scratchpad/gen-akses.php. Jalankan SETELAH ddl-pemantauan-akses-ruang-server.sql.
-- =============================================================
-- BERKAS INI MENGOSONGKAN TABEL LEBIH DULU (lihat DELETE di bawah),
-- supaya dijalankan berapa kali pun hasilnya tetap 50 baris ini saja —
-- tidak menumpuk di atas sample versi lama. Sample versi pertama sempat
-- memuat vendor/auditor/pegawai karangan; DELETE ini yang membuangnya.
--
-- AWAS: kalau tabel ini sudah berisi catatan akses SUNGGUHAN, hapus dulu
-- baris DELETE-nya — kalau tidak, catatan asli itu ikut terhapus.
-- =============================================================

DELETE FROM RSTXN_AKSESSERVERS;

INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"01/09/2025 10:21:34","waktuKeluar":"01/09/2025 11:24:34","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Puji","kode":"","tanggal":"01/09/2025 11:24:34"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"11/09/2025 14:18:35","waktuKeluar":"11/09/2025 14:43:35","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Kain lap, kuas","didampingi":"","catatan":"Pemantauan suhu ruang serta pembersihan debu filter AC.","paraf":{"nama":"Puji","kode":"","tanggal":"11/09/2025 14:43:35"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"18/09/2025 14:09:59","waktuKeluar":"18/09/2025 15:17:59","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"18/09/2025 15:17:59"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"30/09/2025 09:57:35","waktuKeluar":"30/09/2025 10:21:35","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Senter","didampingi":"","catatan":"Pengecekan hardware server: status disk, power supply, dan unit pendingin.","paraf":{"nama":"Soim","kode":"","tanggal":"30/09/2025 10:21:35"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"07/10/2025 13:49:10","waktuKeluar":"07/10/2025 14:30:10","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Senter, kain lap","didampingi":"","catatan":"Pengecekan kondisi fisik hardware server (indikator, kipas, kabel daya).","paraf":{"nama":"Soim","kode":"","tanggal":"07/10/2025 14:30:10"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"10/10/2025 10:29:20","waktuKeluar":"10/10/2025 11:10:20","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Soim","kode":"","tanggal":"10/10/2025 11:10:20"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"16/10/2025 16:22:16","waktuKeluar":"16/10/2025 17:19:16","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"16/10/2025 17:19:16"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"04/11/2025 08:46:50","waktuKeluar":"04/11/2025 09:33:50","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Soim","kode":"","tanggal":"04/11/2025 09:33:50"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"11/11/2025 14:03:15","waktuKeluar":"11/11/2025 14:41:15","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"lainnya","keperluanLain":"Update program SIMRS","membawaPerangkat":"Laptop","didampingi":"","catatan":"Penerapan versi baru program SIMRS dan pengecekan layanan.","paraf":{"nama":"Anshary","kode":"","tanggal":"11/11/2025 14:41:15"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"18/11/2025 09:24:48","waktuKeluar":"18/11/2025 09:58:48","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Pengecekan lampu indikator perangkat jaringan dan storage.","paraf":{"nama":"Puji","kode":"","tanggal":"18/11/2025 09:58:48"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"26/11/2025 14:59:27","waktuKeluar":"26/11/2025 16:12:27","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"26/11/2025 16:12:27"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"05/12/2025 09:03:08","waktuKeluar":"05/12/2025 10:12:08","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"lainnya","keperluanLain":"Update program SIMRS","membawaPerangkat":"Laptop","didampingi":"","catatan":"Update program SIMRS di server aplikasi.","paraf":{"nama":"Anshary","kode":"","tanggal":"05/12/2025 10:12:08"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"11/12/2025 08:09:48","waktuKeluar":"11/12/2025 09:18:48","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Puji","kode":"","tanggal":"11/12/2025 09:18:48"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"12/12/2025 16:27:01","waktuKeluar":"12/12/2025 17:10:01","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"12/12/2025 17:10:01"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"29/12/2025 09:13:50","waktuKeluar":"29/12/2025 10:48:50","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"lainnya","keperluanLain":"Update program SIMRS","membawaPerangkat":"Laptop","didampingi":"","catatan":"Penerapan versi baru program SIMRS dan pengecekan layanan.","paraf":{"nama":"Anshary","kode":"","tanggal":"29/12/2025 10:48:50"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"02/01/2026 13:52:38","waktuKeluar":"02/01/2026 15:21:38","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"02/01/2026 15:21:38"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"06/01/2026 12:32:12","waktuKeluar":"06/01/2026 13:00:12","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Senter","didampingi":"","catatan":"Pengecekan hardware server: status disk, power supply, dan unit pendingin.","paraf":{"nama":"Soim","kode":"","tanggal":"06/01/2026 13:00:12"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"15/01/2026 10:20:06","waktuKeluar":"15/01/2026 11:08:06","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Soim","kode":"","tanggal":"15/01/2026 11:08:06"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"22/01/2026 10:48:42","waktuKeluar":"22/01/2026 11:20:42","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Kain lap, kuas","didampingi":"","catatan":"Pemantauan suhu ruang serta pembersihan debu filter AC.","paraf":{"nama":"Anshary","kode":"","tanggal":"22/01/2026 11:20:42"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"30/01/2026 10:58:36","waktuKeluar":"30/01/2026 11:38:36","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Thermometer ruangan","didampingi":"","catatan":"Pemantauan suhu ruang dan status AC.","paraf":{"nama":"Puji","kode":"","tanggal":"30/01/2026 11:38:36"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"30/01/2026 12:29:20","waktuKeluar":"30/01/2026 14:19:20","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"lainnya","keperluanLain":"Update program SIMRS","membawaPerangkat":"Laptop","didampingi":"","catatan":"Update program dan restart layanan aplikasi.","paraf":{"nama":"Anshary","kode":"","tanggal":"30/01/2026 14:19:20"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"03/02/2026 09:39:50","waktuKeluar":"03/02/2026 10:34:50","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Soim","kode":"","tanggal":"03/02/2026 10:34:50"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"13/02/2026 13:51:33","waktuKeluar":"13/02/2026 15:20:33","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"13/02/2026 15:20:33"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"04/03/2026 08:19:44","waktuKeluar":"04/03/2026 09:07:44","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Puji","kode":"","tanggal":"04/03/2026 09:07:44"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"06/03/2026 12:38:43","waktuKeluar":"06/03/2026 14:02:43","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"lainnya","keperluanLain":"Update program SIMRS","membawaPerangkat":"Laptop","didampingi":"","catatan":"Update program SIMRS di server aplikasi.","paraf":{"nama":"Anshary","kode":"","tanggal":"06/03/2026 14:02:43"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"23/03/2026 16:45:34","waktuKeluar":"23/03/2026 18:18:34","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"23/03/2026 18:18:34"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"27/03/2026 12:02:43","waktuKeluar":"27/03/2026 12:46:43","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Thermometer ruangan","didampingi":"","catatan":"Pemantauan suhu ruang dan status AC.","paraf":{"nama":"Puji","kode":"","tanggal":"27/03/2026 12:46:43"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"08/04/2026 08:43:29","waktuKeluar":"08/04/2026 09:22:29","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Puji","kode":"","tanggal":"08/04/2026 09:22:29"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"24/04/2026 08:55:31","waktuKeluar":"24/04/2026 09:19:31","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Thermometer ruangan","didampingi":"","catatan":"Pemantauan suhu ruang dan status AC.","paraf":{"nama":"Soim","kode":"","tanggal":"24/04/2026 09:19:31"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"27/04/2026 13:24:28","waktuKeluar":"27/04/2026 14:43:28","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"27/04/2026 14:43:28"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"01/05/2026 10:28:22","waktuKeluar":"01/05/2026 10:56:22","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Pengecekan lampu indikator perangkat jaringan dan storage.","paraf":{"nama":"Soim","kode":"","tanggal":"01/05/2026 10:56:22"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"12/05/2026 08:38:10","waktuKeluar":"12/05/2026 09:05:10","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Toolkit, cable tie","didampingi":"","catatan":"Pengecekan hardware server dan perapian kabel rak.","paraf":{"nama":"Puji","kode":"","tanggal":"12/05/2026 09:05:10"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"12/05/2026 15:24:04","waktuKeluar":"12/05/2026 16:34:04","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"12/05/2026 16:34:04"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"25/05/2026 08:01:04","waktuKeluar":"25/05/2026 08:54:04","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Puji","kode":"","tanggal":"25/05/2026 08:54:04"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"15/06/2026 10:05:33","waktuKeluar":"15/06/2026 10:43:33","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Kain lap, kuas","didampingi":"","catatan":"Pemantauan suhu ruang serta pembersihan debu filter AC.","paraf":{"nama":"Soim","kode":"","tanggal":"15/06/2026 10:43:33"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"19/06/2026 14:15:04","waktuKeluar":"19/06/2026 15:27:04","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"19/06/2026 15:27:04"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"22/06/2026 09:57:58","waktuKeluar":"22/06/2026 10:43:58","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Puji","kode":"","tanggal":"22/06/2026 10:43:58"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"25/06/2026 14:08:32","waktuKeluar":"25/06/2026 14:43:32","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Toolkit, cable tie","didampingi":"","catatan":"Pengecekan hardware server dan perapian kabel rak.","paraf":{"nama":"Anshary","kode":"","tanggal":"25/06/2026 14:43:32"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"29/06/2026 09:31:43","waktuKeluar":"29/06/2026 09:59:43","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Senter, kain lap","didampingi":"","catatan":"Pengecekan kondisi fisik hardware server (indikator, kipas, kabel daya).","paraf":{"nama":"Soim","kode":"","tanggal":"29/06/2026 09:59:43"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"01/07/2026 08:00:25","waktuKeluar":"01/07/2026 08:56:25","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Puji","kode":"","tanggal":"01/07/2026 08:56:25"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"08/07/2026 13:40:14","waktuKeluar":"08/07/2026 13:56:14","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Senter, kain lap","didampingi":"","catatan":"Pengecekan kondisi fisik hardware server (indikator, kipas, kabel daya).","paraf":{"nama":"Anshary","kode":"","tanggal":"08/07/2026 13:56:14"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"13/07/2026 16:15:57","waktuKeluar":"13/07/2026 17:01:57","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"13/07/2026 17:01:57"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"15/07/2026 12:38:47","waktuKeluar":"15/07/2026 14:25:47","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"lainnya","keperluanLain":"Update program SIMRS","membawaPerangkat":"Laptop","didampingi":"","catatan":"Update program dan restart layanan aplikasi.","paraf":{"nama":"Anshary","kode":"","tanggal":"15/07/2026 14:25:47"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"24/07/2026 14:16:50","waktuKeluar":"24/07/2026 14:54:50","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Pengecekan lampu indikator perangkat jaringan dan storage.","paraf":{"nama":"Soim","kode":"","tanggal":"24/07/2026 14:54:50"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"05/08/2026 09:00:46","waktuKeluar":"05/08/2026 09:51:46","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"perawatanRutin","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Mendampingi petugas kebersihan membersihkan ruang server.","paraf":{"nama":"Puji","kode":"","tanggal":"05/08/2026 09:51:46"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"10/08/2026 10:35:33","waktuKeluar":"10/08/2026 10:52:33","nama":"Soim","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"","didampingi":"","catatan":"Pengecekan lampu indikator perangkat jaringan dan storage.","paraf":{"nama":"Soim","kode":"","tanggal":"10/08/2026 10:52:33"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"13/08/2026 11:31:49","waktuKeluar":"13/08/2026 12:55:49","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"lainnya","keperluanLain":"Update program SIMRS","membawaPerangkat":"Laptop","didampingi":"","catatan":"Update program SIMRS di server aplikasi.","paraf":{"nama":"Anshary","kode":"","tanggal":"13/08/2026 12:55:49"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"14/08/2026 14:16:07","waktuKeluar":"14/08/2026 15:16:07","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"backupRestore","keperluanLain":"","membawaPerangkat":"Hardisk eksternal","didampingi":"","catatan":"Backup data bulanan ke media eksternal.","paraf":{"nama":"Anshary","kode":"","tanggal":"14/08/2026 15:16:07"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"17/08/2026 09:43:43","waktuKeluar":"17/08/2026 10:43:43","nama":"Anshary","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"lainnya","keperluanLain":"Update program SIMRS","membawaPerangkat":"Laptop","didampingi":"","catatan":"Penerapan versi baru program SIMRS dan pengecekan layanan.","paraf":{"nama":"Anshary","kode":"","tanggal":"17/08/2026 10:43:43"}}');
INSERT INTO RSTXN_AKSESSERVERS (AKSESSERVER_NO, AKSESSERVER_JSON) VALUES (SEQ_AKSESSERVERS.NEXTVAL, '{"waktu":"27/08/2026 08:05:46","waktuKeluar":"27/08/2026 08:42:46","nama":"Puji","unitInstansi":"IT / SIMRS","jenisPengunjung":"internal","keperluan":"pemantauan","keperluanLain":"","membawaPerangkat":"Thermometer ruangan","didampingi":"","catatan":"Pembacaan suhu ruang di luar jadwal pemantauan bulanan.","paraf":{"nama":"Puji","kode":"","tanggal":"27/08/2026 08:42:46"}}');

COMMIT;
